# -*- coding: utf-8 -*-
"""4110E108_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-ihnulaX-bamSOa7sp4Ze_BdIizk6_Q
"""

print("4111001671")
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change