# -*- coding: utf-8 -*-
"""4110E108_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-ihnulaX-bamSOa7sp4Ze_BdIizk6_Q
"""

print("4111001671")
def my_function(child3, child2, child1):
  print("The youngest child is " + child3)

my_function(child1 = "Emil", child2 = "Tobias", child3 = "Linus")