# -*- coding: utf-8 -*-
"""4110E108_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-ihnulaX-bamSOa7sp4Ze_BdIizk6_Q
"""

print("4111001671")
a = '''Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.'''
print(a)