# -*- coding: utf-8 -*-
"""4110E108_1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-ihnulaX-bamSOa7sp4Ze_BdIizk6_Q
"""

print("4111001671")
def my_function(fname):
  print(fname + " Refsnes")

my_function("Emil")
my_function("Tobias")
my_function("Linus")