# -*- coding: utf-8 -*-
"""41110E108

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FaMjJK0PF_hwBR7xMBOLoUeYJ80mTeHg
"""

print("This is DD speaking")
print("Hello, World!")